return {
    W1EarlyCommand = function(self) self:finishtweening(); self:shadowlength(0); self:y(0); self:diffusealpha(1); self:zoom(0.9*1.2); self:smooth(0.05); self:zoom(0.75*1.2); self:sleep(0.8); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(1.3*1.2); self:diffusealpha(0); self:glowblink(); self:effectperiod(0.05); self:effectcolor1(color("1,1,1,0")); self:effectcolor2(color("1,1,1,0.25")); end;
    W1LateCommand = function(self) self:finishtweening(); self:shadowlength(0); self:y(0); self:diffusealpha(1); self:zoom(0.9*1.2); self:smooth(0.05); self:zoom(0.75*1.2); self:sleep(0.8); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(1.3*1.2); self:diffusealpha(0); self:glowblink(); self:effectperiod(0.05); self:effectcolor1(color("1,1,1,0")); self:effectcolor2(color("1,1,1,0.25")); end;
    W2EarlyCommand = function(self) self:finishtweening(); self:y(0); self:shadowlength(0); self:diffusealpha(1); self:zoom(0.9*1.2); self:smooth(0.05); self:zoom(0.75*1.2); self:sleep(0.5); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(2*1.2); self:diffusealpha(0); end;
    W2LateCommand = function(self) self:finishtweening(); self:y(0); self:shadowlength(0); self:diffusealpha(1); self:zoom(0.9*1.2); self:smooth(0.05); self:zoom(0.75*1.2); self:sleep(0.5); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(2*1.2); self:diffusealpha(0); end;
    W3EarlyCommand = function(self) self:finishtweening(); self:y(0); self:shadowlength(0); self:diffusealpha(1); self:zoom(0.9*1.2); self:smooth(0.05); self:zoom(0.75*1.2); self:sleep(0.5); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(2*1.2); self:diffusealpha(0); end;
    W3LateCommand = function(self) self:finishtweening(); self:y(0); self:shadowlength(0); self:diffusealpha(1); self:zoom(0.9*1.2); self:smooth(0.05); self:zoom(0.75*1.2); self:sleep(0.5); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(2*1.2); self:diffusealpha(0); end;
    W4EarlyCommand = function(self) self:finishtweening(); self:y(0); self:shadowlength(0); self:diffusealpha(1); self:zoom(0.9*1.2); self:smooth(0.05); self:zoom(0.75*1.2); self:sleep(0.5); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(2*1.2); self:diffusealpha(0); end;
    W4LateCommand = function(self) self:finishtweening(); self:y(0); self:shadowlength(0); self:diffusealpha(1); self:zoom(0.9*1.2); self:smooth(0.05); self:zoom(0.75*1.2); self:sleep(0.5); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(2*1.2); self:diffusealpha(0); end;
    W5EarlyCommand = function(self) self:finishtweening(); self:y(0); self:shadowlength(0); self:diffusealpha(1); self:zoom(0.75*1.2); self:vibrate(); self:effectmagnitude(1,2,2); self:sleep(0.5); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(2*1.2); self:diffusealpha(0); end;
    W5LateCommand = function(self) self:finishtweening(); self:y(0); self:shadowlength(0); self:diffusealpha(1); self:zoom(0.75*1.2); self:vibrate(); self:effectmagnitude(1,2,2); self:sleep(0.5); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(2*1.2); self:diffusealpha(0); end;
    MissEarlyCommand = function(self) self:finishtweening(); self:y(0); self:shadowlength(0); self:diffusealpha(1); self:zoom(0.75*1.2); self:y(-20); self:smooth(0.8); self:y(20); self:sleep(0.5); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(2*1.2); self:diffusealpha(0); end;
    MissLateCommand = function(self) self:finishtweening(); self:y(0); self:shadowlength(0); self:diffusealpha(1); self:zoom(0.75*1.2); self:y(-20); self:smooth(0.8); self:y(20); self:sleep(0.5); self:smooth(0.1); self:zoomy(0.5*1.2); self:zoomx(2*1.2); self:diffusealpha(0); end;
};